// Pure transform: a tenant's live schema → TypeScript types, so check() calls
// are compile-time-verified against the deployed schema. IO-free and
// deterministic (the CLI does the fetch + file write).

import type { SchemaDocument } from './schema';

export interface CodegenOptions {
    version: number;
    tenant?: string;
    /** Epoch ms; pass it in so the transform stays deterministic for tests. */
    updatedAt?: number;
}

function unionOf(names: string[]): string {
    if (names.length === 0) return 'never';
    return names.map((n) => JSON.stringify(n)).join(' | ');
}

/**
 * Emit an `AuthzSchema` interface (one entry per object type with its permission
 * and relation name unions), plus `ObjectType`/`PermissionOf` helpers. The
 * built-in `user` type is synthesized: the server strips it from the returned
 * document, but relations legitimately reference it as a subject type.
 *
 * Consume it by parameterizing the client — `authgravity<AuthzSchema>({...})` —
 * so `check({ type, id, permission })` only accepts permissions that exist on
 * that type. (Use the discriminated object form, never a bare `type:id`
 * string: TS widens `"document:" + id` to `string` and silently drops all
 * checking.)
 */
export function schemaToTypes(doc: SchemaDocument, opts: CodegenOptions): string {
    const defs = doc.definitions ?? {};
    const lines: string[] = [];

    lines.push('// GENERATED by `authgravity schema types` — do not edit by hand.');
    if (opts.tenant) lines.push(`// tenant: ${opts.tenant}`);
    lines.push(`// schema version: ${opts.version}`);
    if (opts.updatedAt) lines.push(`// schema updated_at: ${opts.updatedAt}`);
    lines.push('');
    lines.push(`export const SCHEMA_VERSION = ${opts.version};`);
    lines.push('');
    lines.push('export interface AuthzSchema {');

    for (const [typeName, def] of Object.entries(defs)) {
        const perms = Object.keys(def.permissions ?? {});
        const rels = Object.keys(def.relations ?? {});
        lines.push(`    ${typeName}: { permissions: ${unionOf(perms)}; relations: ${unionOf(rels)} };`);
    }
    // Synthesized built-in: a subject type with no permissions/relations.
    if (!('user' in defs)) {
        lines.push('    user: { permissions: never; relations: never };');
    }

    lines.push('}');
    lines.push('');
    lines.push('export type ObjectType = keyof AuthzSchema;');
    lines.push("export type PermissionOf<T extends ObjectType> = AuthzSchema[T]['permissions'];");
    lines.push("export type RelationOf<T extends ObjectType> = AuthzSchema[T]['relations'];");
    lines.push('');

    return lines.join('\n');
}
